//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.DealerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DealerService.IDealerService")]
    public interface IDealerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDealerService/GetDealers", ReplyAction="http://tempuri.org/IDealerService/GetDealersResponse")]
        ApplicationService.DTOs.DealerDTO[] GetDealers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDealerService/GetDealers", ReplyAction="http://tempuri.org/IDealerService/GetDealersResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.DealerDTO[]> GetDealersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDealerService/GetDealersByAge", ReplyAction="http://tempuri.org/IDealerService/GetDealersByAgeResponse")]
        ApplicationService.DTOs.DealerDTO[] GetDealersByAge(int age);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDealerService/GetDealersByAge", ReplyAction="http://tempuri.org/IDealerService/GetDealersByAgeResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.DealerDTO[]> GetDealersByAgeAsync(int age);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDealerService/GetDealerById", ReplyAction="http://tempuri.org/IDealerService/GetDealerByIdResponse")]
        ApplicationService.DTOs.DealerDTO GetDealerById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDealerService/GetDealerById", ReplyAction="http://tempuri.org/IDealerService/GetDealerByIdResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.DealerDTO> GetDealerByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDealerService/PostDealer", ReplyAction="http://tempuri.org/IDealerService/PostDealerResponse")]
        string PostDealer(ApplicationService.DTOs.DealerDTO dealerDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDealerService/PostDealer", ReplyAction="http://tempuri.org/IDealerService/PostDealerResponse")]
        System.Threading.Tasks.Task<string> PostDealerAsync(ApplicationService.DTOs.DealerDTO dealerDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDealerService/PutDealer", ReplyAction="http://tempuri.org/IDealerService/PutDealerResponse")]
        string PutDealer(ApplicationService.DTOs.DealerDTO dealerDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDealerService/PutDealer", ReplyAction="http://tempuri.org/IDealerService/PutDealerResponse")]
        System.Threading.Tasks.Task<string> PutDealerAsync(ApplicationService.DTOs.DealerDTO dealerDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDealerService/DeleteDealer", ReplyAction="http://tempuri.org/IDealerService/DeleteDealerResponse")]
        string DeleteDealer(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDealerService/DeleteDealer", ReplyAction="http://tempuri.org/IDealerService/DeleteDealerResponse")]
        System.Threading.Tasks.Task<string> DeleteDealerAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDealerServiceChannel : MVC.DealerService.IDealerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DealerServiceClient : System.ServiceModel.ClientBase<MVC.DealerService.IDealerService>, MVC.DealerService.IDealerService {
        
        public DealerServiceClient() {
        }
        
        public DealerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DealerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DealerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DealerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ApplicationService.DTOs.DealerDTO[] GetDealers() {
            return base.Channel.GetDealers();
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.DealerDTO[]> GetDealersAsync() {
            return base.Channel.GetDealersAsync();
        }
        
        public ApplicationService.DTOs.DealerDTO[] GetDealersByAge(int age) {
            return base.Channel.GetDealersByAge(age);
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.DealerDTO[]> GetDealersByAgeAsync(int age) {
            return base.Channel.GetDealersByAgeAsync(age);
        }
        
        public ApplicationService.DTOs.DealerDTO GetDealerById(int id) {
            return base.Channel.GetDealerById(id);
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.DealerDTO> GetDealerByIdAsync(int id) {
            return base.Channel.GetDealerByIdAsync(id);
        }
        
        public string PostDealer(ApplicationService.DTOs.DealerDTO dealerDTO) {
            return base.Channel.PostDealer(dealerDTO);
        }
        
        public System.Threading.Tasks.Task<string> PostDealerAsync(ApplicationService.DTOs.DealerDTO dealerDTO) {
            return base.Channel.PostDealerAsync(dealerDTO);
        }
        
        public string PutDealer(ApplicationService.DTOs.DealerDTO dealerDTO) {
            return base.Channel.PutDealer(dealerDTO);
        }
        
        public System.Threading.Tasks.Task<string> PutDealerAsync(ApplicationService.DTOs.DealerDTO dealerDTO) {
            return base.Channel.PutDealerAsync(dealerDTO);
        }
        
        public string DeleteDealer(int id) {
            return base.Channel.DeleteDealer(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteDealerAsync(int id) {
            return base.Channel.DeleteDealerAsync(id);
        }
    }
}
